name: test

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: [self-hosted, self-hosted-linux-s390x-noble-edge]
    steps:
    - name: checkout OVN
      uses: actions/checkout@v4
      with:
        repository: 'ovn-org/ovn'
        path: 'ovn'
        submodules: recursive

    - name: run
      run: |
        set -euxo pipefail
        sudo apt update
        sudo apt -y install automake libtool gcc bc libssl-dev llvm-dev \
            libelf-dev libnuma-dev libpcap-dev ncat libunbound-dev \
            libunwind-dev libudev-dev python3-pip
        sudo update-alternatives --set nc /usr/bin/ncat

        pushd ovn/ovs
        ./boot.sh && ./configure && make -j$(nproc)
        popd

        pushd ovn
        ./boot.sh && ./configure && make -j$(nproc)
        make check TESTSUITEFLAGS=1005 || cat tests/testsuite.log
        popd
